### ISSUE TITLE
Create release v0.5.0

### ISSUE THREAD

**Issue by favoyang** [SinyavtsevIlya/NanoECS#1]
Hi @SinyavtsevIlya ,

Thanks for creating the awesome package. Would please create a github release `v0.5.0`? So the package can be included in upcoming openupm registry ([sneak preview](https://beta.openupm.com)), which is a service that build package directly from git tags that conform semver.

**Comment by SinyavtsevIlya** [comment]
Hey @favoyang! 
Ok, just did it. 
Do you have any suggestions/thoughts on the framework?

**Comment by favoyang** [comment]
@SinyavtsevIlya thanks for the effort. The package will be include in openupm service, preview at 
 https://beta.openupm.com/packages/com.nanory.nanoecs/

For the suggestions, well I haven't read much of the code yet. I think people may curious about the relationship for the framework with unity's DOTS, for pros and cons. Would be good to claim it in the README file.
